packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@biomejs/biome": true
  esbuild: true
overrides:
  "@assistant-ui/tap": 0.9.5
  assistant-cloud: 0.1.36
minimumReleaseAgeExclude:
  - '@assistant-ui/core@0.2.22'
  - '@assistant-ui/react@0.14.28'
  - '@assistant-ui/react-ai-sdk@1.4.0'
  - '@assistant-ui/react-markdown@0.14.7'
  - '@assistant-ui/store@0.2.21'
  - assistant-stream@0.3.27
  - '@assistant-ui/tap@0.9.5'
  - assistant-cloud@0.1.36
  - safe-content-frame@0.0.24
